sonar.projectKey=Dylan-Groux_kasa
sonar.organization=Dylan-Groux

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**

sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx